In [5]:
import numpy as np

In [9]:
class room:
    def __init__(self):
        self.room_size = np.array([4,4])
        self.room= np.zeros((5,5), dtype=int)
        self.banana_pos = np.array([2,2])
        self.monkey_pos = np.array([0,0])
        self.box_pos = np.array([4,4])
        self.jump_height = 1
        self.carry_box = 0
        return
    
    def upadte_objects(self):
        self.room = np.zeros((5,5), dtype=int)  
        if self.carry_box:
            self.room[tuple(self.banana_pos)] = 3
            self.room[tuple(self.monkey_pos)] = 1
        else:
            self.room[tuple(self.banana_pos)] = 3
            self.room[tuple(self.monkey_pos)] = 1
            self.room[tuple(self.box_pos)] = 2
        return
    
    def move_right(self, moves):
        if (self.monkey_pos[1]+moves) > self.room_size[1]:
            print("Can Move this far!!")
        else:
            self.monkey_pos[1] += moves
            mon.upadte_objects()
            print("Moveed right by:", moves)
        return
    
    def move_left(self, moves):
        if (self.monkey_pos[1]-moves) < 0:
            print("Can Move this far!!")
        else:
            self.monkey_pos[1] -= moves
            mon.upadte_objects()
        return
    
    def move_down(self, moves):
        if (self.monkey_pos[0]+moves) > self.room_size[0]:
            print("Can Move this far!!")
        else:
            self.monkey_pos[0] += moves
            mon.upadte_objects()
        return
    
    def move_up(self, moves):
        if (self.monkey_pos[0]-moves) <0:
            print("Can Move this far!!")
        else:
            self.monkey_pos[0] -= moves
            mon.upadte_objects()
        return
    
    def carry(self):
        self.jump_height = 3
        self.carry_box = 1
        mon.upadte_objects()
        return
    
    def jump(self):
        print("jumped")
        if np.array_equal(self.monkey_pos, self.banana_pos) and self.jump_height == 3:
            print("Got Bananas")
            return 1
        else:
            return 0

In [10]:
mon = room()
mon.upadte_objects()
print(mon.room)
mon.move_right(4)
print(mon.room)
mon.move_left(2)
print(mon.room)
mon.move_down(3)
print(mon.room)
mon.move_up(1)
mon.carry()
print(mon.room)
print(mon.monkey_pos)
print(mon.banana_pos)
mon.jump()

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 0 0 0 2]]
Moveed right by: 4
[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 0 0 0 2]]
[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 0 0 0 2]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 3 0 0]
 [0 0 1 0 0]
 [0 0 0 0 2]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[2 2]
[2 2]
jumped
Got Bananas


1

In [11]:
import random
monkey = room()
count = 0
while monkey.jump()==False:
    count+=1
    if np.array_equal(monkey.monkey_pos, monkey.box_pos):
        func = random.randint(0, 5)
    else:
        func = random.randint(0, 4)
    moves = random.randint(1, 5)

    if func == 0:
        monkey.move_left(moves)
    elif func == 1:
        monkey.move_right(moves)
    elif func == 2:
        monkey.move_up(moves)
    elif func == 3:
        monkey.move_down(moves)
    elif func == 4:
        monkey.jump()
    elif func == 5:
        monkey.carry()

print(count)

jumped
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
Moveed right by: 4
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
jumped
jumped
Can Move this far!!
jumped
jumped
Can Move this far!!
jumped
jumped
Can Move this far!!
jumped
jumped
jumped
Moveed right by: 4
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
Moveed right by: 3
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
Moveed right by: 1
jumped
Moveed right by: 1
jumped
jumped
jumped
jumped
jumped
jumped
Can Move this far!!
jumped
Can Move this far!!
jumped
Can Move 